name: Github Actions Demo
on:
  push:
     branches: [main]
  pull_request:
     branches: [main]   
	 
jobs:
   build:
	   ## ....
     runs-on: ubuntu-latest
     steps:

         - name: Check out the repo
           uses: actions/checkout@v4
		 
         - name: Build the docker image
           run: docker build . --file ./Dockerfile --tag inlinescanner-tag:v1.0
         
         - uses: lacework/lw-scanner-action@v1.4.0
           name: Scan container image for vulnerabilities using Lacework
           with:
            LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }}
            LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
            IMAGE_TAG: inlinescanner-tag:v1.0
